import {sqliteTable,text,integer,real,index} from 'drizzle-orm/sqlite-core';
export const projects=sqliteTable('editor_projects',{id:text('id').primaryKey(),owner:text('owner_hash').notNull(),name:text('name').notNull(),revision:integer('revision').notNull().default(0),shared:integer('shared').notNull().default(0),body:text('body').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('editor_projects_owner').on(t.owner)]);
export const files=sqliteTable('editor_files',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()});
// Public reports (anyone) → proposals (AI-assisted, ambassador-approved) → station layers. Photos live in R2.
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),stationKey:text('station_key').notNull(),floor:text('floor'),position:text('position'),view:text('view'),type:text('type').notNull(),description:text('description').notNull().default(''),placeNote:text('place_note').notNull().default(''),status:text('status').notNull(),reporterHash:text('reporter_hash').notNull(),userId:text('user_id'),groupId:text('group_id'),analysis:text('analysis'),history:text('history').notNull(),reason:text('reason'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('reports_station_status').on(t.stationKey,t.status),index('reports_reporter').on(t.reporterHash),index('reports_group').on(t.groupId)]);
// caption/mark: what the reporter says about this photo and where (fractions); preview: a tiny mosaic anyone may see.
export const reportPhotos=sqliteTable('report_photos',{id:text('id').primaryKey(),reportId:text('report_id').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),width:integer('width'),height:integer('height'),caption:text('caption'),mark:text('mark'),viewRole:text('view_role').notNull().default('unknown'),previewSize:integer('preview_size'),createdAt:text('created_at').notNull()},t=>[index('report_photos_report').on(t.reportId)]);
export const proposals=sqliteTable('proposals',{id:text('id').primaryKey(),stationKey:text('station_key').notNull(),reportIds:text('report_ids').notNull(),kind:text('kind').notNull(),target:text('target').notNull(),meta:text('meta'),mime:text('mime'),size:integer('size'),confidence:real('confidence'),status:text('status').notNull(),reviewer:text('reviewer'),reason:text('reason'),createdAt:text('created_at').notNull(),decidedAt:text('decided_at')},t=>[index('proposals_station_status').on(t.stationKey,t.status)]);
export const stationLayers=sqliteTable('station_layers',{stationKey:text('station_key').primaryKey(),revision:integer('revision').notNull().default(0),body:text('body').notNull(),updatedAt:text('updated_at').notNull()});
// Approved operation intent → bounded AI draft job. Never directly changes the public map.
export const reportJobs=sqliteTable('report_jobs',{id:text('id').primaryKey(),reportId:text('report_id').notNull(),stationKey:text('station_key').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),reportVersion:text('report_version').notNull(),actor:text('actor').notNull(),input:text('input').notNull(),plan:text('plan'),questions:text('questions').notNull().default('[]'),error:text('error'),proposalId:text('proposal_id'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('report_jobs_report').on(t.reportId,t.createdAt),index('report_jobs_status').on(t.status,t.updatedAt)]);
// Approvers sign in with a name and password (APPROVERS); only a hash of the session token is stored.
export const approverSessions=sqliteTable('approver_sessions',{tokenHash:text('token_hash').primaryKey(),name:text('name').notNull(),createdAt:text('created_at').notNull(),expiresAt:text('expires_at').notNull()});
export const auditLog=sqliteTable('audit_log',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),detail:text('detail'),createdAt:text('created_at').notNull()},t=>[index('audit_log_action_target').on(t.action,t.target,t.createdAt)]);
