import './style.css';
import {sampleProject,daejeonProject,validateProject,floors,heights,roles,coordinate} from './model.js';
import {createScene} from './scene.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project=daejeonProject(),projectId=null,revision=0,canEdit=true,shared=false,dirty=false,tab='assets',selected=null,scene=null,areaCapture=null,lastPick=null;
const categories={assets:['STRUCTURES','구조물 추가·변경','구조물을 클릭하거나 좌표를 입력하세요. 철거는 숨김으로 보존합니다.'],facades:['FACADES','면별 파사드 관리','정면·우측·후면·좌측을 따로 등록합니다. 권한이 있는 사진만 업로드하세요.'],points:['WAYPOINTS','시설·경로 포인트','지도 위 참고 격자를 클릭한 뒤 역할을 지정하세요. 출도착은 영역도 가능합니다.'],connections:['CONNECTIONS','층간 연결','다른 층의 접속점을 연결합니다. 엘리베이터는 여러 층을 함께 선택하세요.'],routes:['ROUTES','순서대로 동선 연결','포인트를 순서대로 추가하세요. 층을 바꿀 때는 등록한 층간접속점을 이어야 합니다.'],observations:['DATA','유동 데이터 관리','일별·시간별 관측값과 추정값을 구분하고 산출 근거를 남깁니다.']};
const key=()=>tab==='facades'?'assets':tab,record=()=>project[key()].find(r=>r.id===selected),options=(items,value)=>items.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('');
const input=(label,name,value,type='text',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}" ${extra}></label>`;
const select=(label,name,opts,value)=>`<label>${label}<select name="${name}">${options(opts,value)}</select></label>`;
const notice=s=>{$('#notice').textContent=s;$('#notice').classList.add('visible');setTimeout(()=>$('#notice').classList.remove('visible'),5500);};
function status(){ $('#saveStatus').textContent=!canEdit?'공개 읽기 전용 · 복사한 후 편집하세요':dirty?'저장하지 않은 변경사항 있음':projectId?`서버 저장됨 · 버전 ${revision}`:'아직 서버에 저장되지 않은 초안';$('#saveProject').textContent=canEdit?'서버 저장':'내 프로젝트로 복사';}
function changed(){dirty=true;status();scene?.render(project);}
function dialog(html){$('#dialogContent').innerHTML=html;$('#dialog').showModal();}
$('#closeDialog').onclick=()=>$('#dialog').close();
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error||'요청 실패');return v;}
function syncHeader(){$('#projectName').value=project.name;$('#source').value=project.source;$('#tilesetUrl').value=project.tileset_url||'';$('#tilesetUrl').hidden=project.source!=='tileset';status();}
function fields(r){
 let h=input('이름','name',r.name||'')+`<small class="id">${esc(r.id)}</small>`;
 if(['assets','points'].includes(tab))h+=select('층','floor',floors.map(f=>[f,f]),r.floor)+`<div class="coords">${input('경도','lon',r.position[0],'number','step="any" required')}${input('위도','lat',r.position[1],'number','step="any" required')}${input('바닥 높이(m)','height',r.position[2],'number','step="any" required')}</div><p class="hint">지도 클릭으로 좌표 입력 · 높이는 기준고도를 확인하세요.</p>`;
 if(tab==='assets')h+=`<div class="coords">${input('폭(m)','width',r.size[0],'number','step=".1" min=".1" required')}${input('깊이(m)','depth',r.size[1],'number','step=".1" min=".1" required')}${input('높이(m)','sizeHeight',r.size[2],'number','step=".1" min=".1" required')}</div>${input('방향(°)','heading',r.heading,'number','step=".1"')}${input('벽 색상','color',r.color,'color')}${input('기본지도 에셋 ID (선택)','source_id',r.source_id||'')}<label class="check"><input name="hidden" type="checkbox" ${r.hidden?'checked':''}> 철거 / 숨김</label><p class="hint">기본지도 ID가 있으면 해당 모델의 숨김과 파사드 레이어를 관리합니다. 원본 모델의 메시 자체는 변형하지 않습니다.</p>`;
 if(tab==='facades')h=`<h2>${esc(r.name)}</h2>`+select('적용할 면','side',[['front','정면'],['right','우측면'],['back','후면'],['left','좌측면']],'front')+input('이미지 주소','facade_url',r.facades?.front||'','text','placeholder="https://… 또는 업로드"')+'<label>사진 업로드 (PNG/JPEG · 4MB)<input type="file" id="facadeFile" accept="image/png,image/jpeg"></label><img id="facadePreview" alt="파사드 미리보기" '+(r.facades?.front?`src="${esc(r.facades.front)}"`:'hidden')+'><p class="hint">정면을 남쪽으로 두고 방향각만큼 회전합니다. 원근 보정된 사진을 권장합니다.</p>';
 if(tab==='points')h+=select('포인트 역할','role',Object.entries(roles).map(([k,v])=>[k,v[0]]),r.role)+`<button type="button" id="captureArea">${r.area?'영역 다시 지정':'출도착 영역 지정'}</button>${r.area?'<button type="button" id="clearArea">영역 해제 · 점으로</button>':''}<p class="hint" id="areaHint">${r.area?`${r.area.length}개 꼭짓점 영역`:'영역은 출발·도착 역할에서만 지정합니다.'}</p>`;
 if(tab==='connections')h+=select('이동시설','kind',[['stairs','계단'],['escalator','에스컬레이터'],['elevator','엘리베이터']],r.kind)+select('통행 방향','direction',[['both','양방향 / 모든 선택 층 연결'],['forward','선택 목록 순서의 정방향']],r.direction)+'<fieldset><legend>연결할 층간접속점</legend>'+project.points.filter(p=>p.role==='connection').map(p=>`<label class="check"><input name="connectionPoints" type="checkbox" value="${esc(p.id)}" ${r.point_ids.includes(p.id)?'checked':''}> ${esc(p.floor+' · '+p.name)}</label>`).join('')+'</fieldset>';
 if(tab==='routes')h+=`<ol class="route-order">${r.point_ids.map((id,i)=>{const p=project.points.find(p=>p.id===id);return `<li><span>${esc(p?`${p.floor} · ${p.name}`:id)}</span><button type="button" data-order="${i}" data-delta="-1" aria-label="위로">↑</button><button type="button" data-order="${i}" data-delta="1" aria-label="아래로">↓</button><button type="button" data-remove="${i}" aria-label="포인트 제거">×</button></li>`;}).join('')}</ol>`+select('다음 포인트','nextPoint',project.points.map(p=>[p.id,`${p.floor} · ${p.name}`]),'')+'<button id="appendPoint" type="button">＋ 순서에 추가</button>';
 if(tab==='observations')h=select('출도착 원점','origin_id',project.points.filter(p=>p.role==='origin').map(p=>[p.id,p.name]),r.origin_id)+input('기준일','date',r.date,'date','required')+select('집계 시간','hour',[['','일 전체'],...Array.from({length:24},(_,i)=>[String(i),`${i}시`])],r.hour===null?'':String(r.hour))+input('진입량','arrivals',r.arrivals,'number','min="0" required')+input('이탈량','departures',r.departures,'number','min="0" required')+select('값의 성격','value_class',[['observed','관측값'],['estimated','추정값']],r.value_class)+`<label>출처·추정 기준<textarea name="method" rows="4">${esc(r.method)}</textarea></label>`;
 return h+`<div class="form-actions"><button class="primary" type="submit">변경 적용</button>${tab==='facades'?'':`<button type="button" id="removeRecord">등록 해제</button>`}</div>`;
}
function render(){const meta=categories[tab];$('#tabCaption').textContent=meta[0];$('#tabTitle').textContent=meta[1];$('#tabHelp').textContent=meta[2];document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));$('#addRecord').hidden=tab==='facades';const rows=project[key()];$('#recordList').innerHTML=rows.map(r=>`<button data-record="${esc(r.id)}" class="record ${r.id===selected?'selected':''}"><strong>${esc(r.name||[r.date,r.hour===null?'일 전체':r.hour+'시'].join(' · '))}</strong><small>${esc(r.floor||r.id)}${r.hidden?' · 숨김':''}</small></button>`).join('')||'<p class="empty">등록된 항목이 없습니다.</p>';const r=record();$('#recordForm').innerHTML=r?fields(r):'<p class="empty">항목을 선택하거나 추가하세요.</p>';$('#recordForm').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=!canEdit);bindForm();syncHeader();}
function applyForm({quiet=false}={}){const r=record();if(!r||!canEdit)return true;const f=$('#recordForm'),fd=new FormData(f),candidate=structuredClone(r);if(fd.has('name'))candidate.name=fd.get('name');if(['assets','points'].includes(tab)){candidate.floor=fd.get('floor');candidate.position=['lon','lat','height'].map(n=>Number(fd.get(n)));}
 if(tab==='assets'){candidate.size=['width','depth','sizeHeight'].map(n=>Number(fd.get(n)));candidate.heading=Number(fd.get('heading'));candidate.color=fd.get('color');candidate.hidden=fd.has('hidden');candidate.source_id=fd.get('source_id').trim()||undefined;}
 if(tab==='facades'){candidate.facades||={};const url=fd.get('facade_url').trim();if(url)candidate.facades[fd.get('side')]=url;else delete candidate.facades[fd.get('side')];}
 if(tab==='points'){candidate.role=fd.get('role');if(candidate.role!=='origin')delete candidate.area;}
 if(tab==='connections'){candidate.kind=fd.get('kind');candidate.direction=fd.get('direction');candidate.point_ids=fd.getAll('connectionPoints');}
 if(tab==='observations')Object.assign(candidate,{origin_id:fd.get('origin_id'),date:fd.get('date'),hour:fd.get('hour')===''?null:Number(fd.get('hour')),arrivals:Number(fd.get('arrivals')),departures:Number(fd.get('departures')),value_class:fd.get('value_class'),method:fd.get('method')});
 const next=structuredClone(project);next[key()][next[key()].findIndex(x=>x.id===r.id)]=candidate;try{validateProject(next);}catch(e){notice(e.message);return false;}const differs=JSON.stringify(r)!==JSON.stringify(candidate);project=next;if(differs)changed();if(!quiet)notice('변경 레이어에 적용했습니다. 서버 저장으로 보관하세요.');return true;
}
function bindForm(){const f=$('#recordForm');f.onsubmit=e=>{e.preventDefault();if(applyForm())render();};f.oninput=()=>{dirty=true;status();};
 const side=f.elements.side;if(side)side.onchange=()=>{const r=record();f.elements.facade_url.value=r.facades?.[side.value]||'';const im=$('#facadePreview');im.hidden=!f.elements.facade_url.value;if(!im.hidden)im.src=f.elements.facade_url.value;};
 const file=$('#facadeFile');if(file)file.onchange=async()=>{try{const image=file.files[0],selectedSide=f.elements.side.value;if(!image)return;if(!projectId){await save({skipForm:true});}const res=await fetch(`/api/projects/${projectId}/files`,{method:'POST',body:image});const v=await res.json();if(!res.ok)throw Error(v.error);const current=$('#recordForm');current.elements.side.value=selectedSide;current.elements.facade_url.value=v.url;$('#facadePreview').src=v.url;$('#facadePreview').hidden=false;dirty=true;status();notice('업로드 완료 · 변경 적용 후 서버 저장하세요.');}catch(e){notice(e.message);}};
 const area=$('#captureArea');if(area)area.onclick=()=>{if(f.elements.role.value!=='origin'){notice('역할을 출발·도착으로 선택하세요.');return;}areaCapture=[];$('#areaHint').innerHTML='지도에서 꼭짓점을 3개 이상 클릭하세요. <button type="button" id="finishArea">영역 확정</button>';$('#finishArea').onclick=()=>{if(areaCapture.length<3)return notice('3개 이상 지정하세요.');record().area=areaCapture;record().role='origin';areaCapture=null;changed();render();};};
 if($('#clearArea'))$('#clearArea').onclick=()=>{delete record().area;changed();render();};
 if($('#appendPoint'))$('#appendPoint').onclick=()=>{record().name=f.elements.name.value;record().point_ids.push(f.elements.nextPoint.value);changed();render();};
 f.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{record().name=f.elements.name.value;const a=record().point_ids,i=+b.dataset.order,j=i+(+b.dataset.delta);if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];changed();render();});
 f.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{record().point_ids.splice(+b.dataset.remove,1);changed();render();});
 if($('#removeRecord'))$('#removeRecord').onclick=()=>{dialog('<h2>등록을 해제할까요?</h2><p>서버에 저장하기 전까지는 기존 저장본을 다시 불러올 수 있습니다. 철거된 구조물은 등록 해제 대신 숨김을 권장합니다.</p><button id="confirmRemove" class="primary">등록 해제</button>');$('#confirmRemove').onclick=()=>{const next=structuredClone(project);next[key()]=next[key()].filter(r=>r.id!==selected);try{validateProject(next);}catch(e){notice('다른 경로·연결에서 참조 중입니다. '+e.message);return;}project=next;selected=project[key()][0]?.id;$('#dialog').close();changed();render();};};
}
function selectRecord(id){selected=id;render();const p=record()?.position;if(p)scene?.focus(p);}
$('#recordList').onclick=e=>{const b=e.target.closest('[data-record]');if(b){if(record()&&!applyForm({quiet:true}))return;selectRecord(b.dataset.record);}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(record()&&!applyForm({quiet:true}))return;areaCapture=null;tab=b.dataset.tab;selected=project[key()][0]?.id;render();});
$('#addRecord').onclick=()=>{if(!canEdit)return notice('공개 프로젝트를 먼저 복사하세요.');if(record()&&!applyForm({quiet:true}))return;const id=crypto.randomUUID(),floor=$('#floor').value,p=lastPick?.position||coordinate(0,0,heights[floor]);let r;
 if(tab==='assets')r={id,name:'새 구조물',floor,position:p,size:[4,3,3],heading:0,color:'#73a194',hidden:false,facades:{}};
 if(tab==='points')r={id,name:'새 포인트',floor,position:p,role:'via'};
 if(tab==='connections'){const pts=project.points.filter(p=>p.role==='connection');if(new Set(pts.map(p=>p.floor)).size<2)return notice('서로 다른 층의 층간접속점을 먼저 2개 이상 등록하세요.');r={id,name:'새 층간연결',kind:'elevator',point_ids:[pts[0],pts.find(p=>p.floor!==pts[0].floor)].map(p=>p.id),direction:'both'};}
 if(tab==='routes'&&project.points.length<2)return notice('경로를 이을 포인트를 먼저 2개 이상 등록하세요.');if(tab==='routes')r={id,name:'새 이동동선',point_ids:project.points.slice(0,2).map(p=>p.id)};
 if(tab==='observations'&&!project.points.some(p=>p.role==='origin'))return notice('출발·도착 포인트를 먼저 등록하세요.');if(tab==='observations')r={id,origin_id:project.points.find(p=>p.role==='origin')?.id||'',date:new Date().toISOString().slice(0,10),hour:null,arrivals:0,departures:0,value_class:'observed',method:''};
 if(r){project[key()].push(r);selected=id;changed();render();}};
async function save({skipForm=false}={}){if(!skipForm&&record()&&!applyForm({quiet:true}))throw Error('선택 항목을 확인하세요.');project.name=$('#projectName').value.trim();validateProject(project);if(!projectId||!canEdit){const v=await api('/api/projects','POST',{project});projectId=v.id;revision=v.revision;canEdit=true;shared=false;history.replaceState(null,'','?project='+projectId);}else{const v=await api('/api/projects/'+projectId,'PUT',{project,revision,shared});revision=v.revision;}dirty=false;status();render();return{id:projectId,revision};}
$('#saveProject').onclick=()=>save().then(()=>notice('서버 저장 완료')).catch(e=>notice(e.message));
$('#projectName').oninput=()=>{project.name=$('#projectName').value;dirty=true;status();};
function exportProject(){if(record())applyForm({quiet:true});const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ya-nerd-station-project.json';a.click();URL.revokeObjectURL(url);}
$('#exportProject').onclick=exportProject;
async function load(v){project=v.project;projectId=v.id||null;revision=v.revision||0;canEdit=v.canEdit!==false;shared=!!v.shared;dirty=false;selected=project[key()][0]?.id;render();await scene?.connect(project);}
function guard(action){if(!dirty)return action();dialog('<h2>저장하지 않은 변경이 있습니다</h2><p>JSON으로 내보내거나 서버에 저장한 뒤 다른 프로젝트를 여세요.</p><button id="discardChanges">변경 버리고 계속</button>');$('#discardChanges').onclick=()=>{$('#dialog').close();action();};}
$('#newProject').onclick=()=>guard(()=>{history.replaceState(null,'',location.pathname+(location.search.includes('scene=local')?'?scene=local':''));load({project:daejeonProject()});});
$('#openProjects').onclick=()=>guard(async()=>{try{const list=await api('/api/projects');dialog('<h2>이 브라우저의 프로젝트</h2><p>서버에 저장되며, 이 브라우저의 편집 쿠키로 접근합니다. 계정 로그인 기능은 아닙니다.</p>'+list.map(p=>`<button class="record" data-load="${p.id}">${esc(p.name)} <small>v${p.revision} · ${p.shared?'공개':'비공개'}</small></button>`).join(''));$('#dialogContent').querySelectorAll('[data-load]').forEach(b=>b.onclick=async()=>{try{const v=await api('/api/projects/'+b.dataset.load);history.replaceState(null,'','?project='+v.id);await load(v);$('#dialog').close();}catch(e){notice(e.message);}});}catch(e){notice(e.message);}});
$('#importProject').onchange=e=>{const file=e.target.files[0];if(!file)return;guard(async()=>{try{if(file.size>2_000_000)throw Error('JSON은 2MB까지 가능합니다.');const v=validateProject(JSON.parse(await file.text()));await load({project:v});history.replaceState(null,'','/');dirty=true;status();notice('새 초안으로 가져왔습니다. 서버 저장으로 별도 보관하세요.');}catch(e){notice(e.message);}});e.target.value='';};
$('#share').onclick=async()=>{if(!canEdit)return notice('공개 프로젝트는 복사한 뒤 공유하세요.');dialog(`<h2>프로젝트 공개 링크</h2><p>공개하면 시설 정보·사진·연계 데이터를 링크가 있는 누구나 볼 수 있습니다. 공개 권한이 있는 자료인지 확인하세요. 다른 사용자는 복사 후 편집할 수 있습니다.</p><label class="check"><input id="shareEnabled" type="checkbox" ${shared?'checked':''}> 이 프로젝트 공개</label><button id="saveSharing" class="primary">공개 설정 저장</button><p id="shareLink"></p>`);$('#saveSharing').onclick=async()=>{try{const before=shared,wanted=$('#shareEnabled').checked;shared=wanted;try{await save();if(wanted!==shared){shared=wanted;await save();}}catch(e){shared=before;throw e;}$('#shareLink').textContent=shared?location.origin+'/?project='+projectId:'공개가 해제되었습니다.';}catch(e){notice(e.message);}};};
$('#help').onclick=()=>dialog('<h2>함께 고치는 역 지도</h2><ol><li>샘플 또는 기본지도를 선택합니다.</li><li>구조물·파사드와 포인트를 등록합니다.</li><li>층간접속점을 연결한 뒤 이동동선을 순서대로 정리합니다.</li><li>연계 데이터의 출처·추정 기준을 입력합니다.</li><li>서버 저장 후 필요할 때만 공개 링크를 만듭니다.</li></ol><p>브이월드 연결은 해당 서버의 접근 정책·네트워크에 영향을 받습니다. 기본지도 데이터는 재배포하지 않습니다. 샘플은 실제 역 시설·통행가능성을 보증하지 않습니다.</p><p>이 도구는 브라우저 쿠키 기반 시연용 편집 권한을 사용합니다. 쿠키 삭제 전 JSON을 내보내세요. JSON에는 업로드 이미지의 주소만 포함됩니다. 다른 서버로 옮길 때 사진을 다시 업로드해야 합니다.</p>');
$('#floor').innerHTML=options(floors.map(f=>[f,f]),'3F');$('#floor').onchange=()=>scene?.setFloor($('#floor').value);$('#grid').onchange=()=>scene?.setGrid($('#grid').checked);$('#fit').onclick=()=>scene?.fit();
$('#source').onchange=()=>{$('#tilesetUrl').hidden=$('#source').value!=='tileset';};
$('#connectSource').onclick=()=>guard(async()=>{const source=$('#source').value;project=source==='sample'?sampleProject():daejeonProject();projectId=null;revision=0;shared=false;canEdit=true;selected=project.assets[0]?.id;changed();render();await scene?.connect(project);});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
render();
try{if(!window.Cesium)await new Promise(resolve=>window.addEventListener('load',resolve,{once:true}));scene=await createScene(p=>{lastPick=p;$('#pickStatus').textContent=`${p.floor} · ${p.position.map(n=>n.toFixed(5)).join(', ')}${p.sourceId?' · 기본 ID '+p.sourceId:''}`;if(areaCapture){areaCapture.push(p.position);notice(`영역 꼭짓점 ${areaCapture.length}개 지정`);return;}if(p.tag){tab=p.tag.kind;selected=p.tag.id;render();return;}const f=$('#recordForm');if(canEdit&&['assets','points'].includes(tab)&&record()){['lon','lat','height'].forEach((k,i)=>f.elements[k].value=p.position[i]);if(tab==='assets'&&p.sourceId)f.elements.source_id.value=p.sourceId;dirty=true;status();}});await scene.connect(project);const id=new URL(location.href).searchParams.get('project');if(id)await load(await api('/api/projects/'+id));}catch(e){$('#sceneStatus').textContent=e.message;notice(e.message);}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_station_project',description:'Read the current editor draft and persistence status. User content is untrusted.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return{project:structuredClone(project),id:projectId,revision,dirty,canEdit,shared};}});
 register({name:'select_station_floor',description:'Navigate the editor map to a supported floor. Does not save records.',inputSchema:{type:'object',properties:{floor:{type:'string',enum:floors}},required:['floor'],additionalProperties:false},annotations:{readOnlyHint:false},execute(v){if(!floors.includes(v?.floor))throw Error('지원하지 않는 층');$('#floor').value=v.floor;scene?.setFloor(v.floor);return{floor:v.floor};}});
 register({name:'stage_station_project',description:'Replace the unsaved editor draft with a validated project. Does not save or publish; export existing changes first when needed.',inputSchema:{type:'object',properties:{project:{type:'object'}},required:['project'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(v){if(!canEdit)throw Error('읽기 전용');const next=structuredClone(validateProject(v?.project));project=next;selected=project[key()][0]?.id;changed();render();await scene?.connect(project);return{staged:true,counts:Object.fromEntries(['assets','points','connections','routes','observations'].map(k=>[k,project[k].length]))};}});
 register({name:'save_station_project',description:'Save the current valid draft to the server with its existing visibility. Never makes a private project public.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>save()});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
