import './style.css';
import {sampleProject,daejeonProject,stationProject,validateProject,floors,heights,roles,coordinate} from './model.js';
import {stations,stationOf,saveLocked,seoulOrigin,validateStation,ktxCatalog} from './stations.js';
import {adaptSeoulSnapshot} from './seoul-snapshot.js';
import {createScene} from './scene.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project=stationProject(),projectId=null,revision=0,canEdit=true,shared=false,dirty=false,tab='assets',selected=null,scene=null,areaCapture=null,lastPick=null;
let recordQuery='';
const categories={assets:['STRUCTURES','구조물 추가·변경','구조물을 클릭하거나 좌표를 입력하세요. 철거는 숨김으로 보존합니다.'],facades:['FACADES','면별 파사드 관리','정면·우측·후면·좌측을 따로 등록합니다. 권한이 있는 사진만 업로드하세요.'],points:['WAYPOINTS','시설·경로 포인트','지도 위 참고 격자를 클릭한 뒤 역할을 지정하세요. 출도착은 영역도 가능합니다.'],connections:['CONNECTIONS','층간 연결','다른 층의 접속점을 연결합니다. 엘리베이터는 여러 층을 함께 선택하세요.'],routes:['ROUTES','순서대로 동선 연결','포인트를 순서대로 추가하세요. 층을 바꿀 때는 등록한 층간접속점을 이어야 합니다.'],observations:['DATA','유동 데이터 관리','일별·시간별 관측값과 추정값을 구분하고 산출 근거를 남깁니다.']};
categories.changes=['CURRENTIZATION','현장 변경 설정','추가·이동·숨김·철거 설정 전체입니다. 세부 메시 설정은 JSON으로 열람하며 임시 초안으로 편집합니다. 지도에는 확정 모델이 표시됩니다.'];
categories.facilities=['FACILITIES','시설 등록 정보','확정 시설과 등록 해제된 시설을 함께 확인합니다. 보행 출입점과 시설 위치는 별도입니다.'];
categories.origins=['ORIGINS','유동인구 원점','외부 원점은 실내지도에 억지로 표시하지 않습니다. 실내 출도착점·영역에 연결합니다.'];
const key=()=>tab==='facades'?'assets':tab,record=()=>(project[key()]||[]).find(r=>r.id===selected),options=(items,value)=>items.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('');
const input=(label,name,value,type='text',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}" ${extra}></label>`;
const select=(label,name,opts,value)=>`<label>${label}<select name="${name}">${options(opts,value)}</select></label>`;
const notice=s=>{$('#notice').textContent=s;$('#notice').classList.add('visible');setTimeout(()=>$('#notice').classList.remove('visible'),5500);};
function status(){const locked=saveLocked(project);$('#juryNotice').hidden=!locked;$('#saveStatus').textContent=locked?'서울역 심사 고정본 · 열람·임시 편집 가능 / 서버 저장 잠금':!canEdit?'공개 읽기 전용 · 복사한 후 편집하세요':dirty?'저장하지 않은 변경사항 있음':projectId?`서버 저장됨 · 버전 ${revision}`:'아직 서버에 저장되지 않은 초안';$('#saveProject').textContent=locked?'심사 기간 · 저장 잠금':canEdit?'서버 저장':'내 프로젝트로 복사';$('#saveProject').disabled=locked;$('#share').disabled=locked;}
function changed(){dirty=true;status();scene?.render(project);}
function dialog(html){$('#dialogContent').innerHTML=html;$('#dialog').showModal();}
$('#closeDialog').onclick=()=>$('#dialog').close();
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error||'요청 실패');return v;}
function syncHeader(){$('#projectName').value=project.name;const station=stationOf(project);if(![...$('#source').options].some(o=>o.value===station.id))$('#source').add(new Option(station.name+' · 사용자 연결',station.id));$('#source').value=project.source==='sample'?'sample':station.id;const current=$('#floor').value;$('#floor').innerHTML=options(station.floors.map(f=>[f,f]),station.floors.includes(current)?current:station.default_floor);status();}
function fields(r){
 let h=input('이름','name',r.name||'')+`<small class="id">${esc(r.id)}</small>`;
 if(['assets','points'].includes(tab))h+=select('층','floor',stationOf(project).floors.map(f=>[f,f]),r.floor)+`<div class="coords">${input('경도','lon',r.position[0],'number','step="any" required')}${input('위도','lat',r.position[1],'number','step="any" required')}${input('바닥 높이(m)','height',r.position[2],'number','step="any" required')}</div><p class="hint">지도 클릭으로 좌표 입력 · 높이는 기준고도를 확인하세요.</p>`;
 if(tab==='assets')h+=`<div class="coords">${input('폭(m)','width',r.size[0],'number','step=".1" min=".1" required')}${input('깊이(m)','depth',r.size[1],'number','step=".1" min=".1" required')}${input('높이(m)','sizeHeight',r.size[2],'number','step=".1" min=".1" required')}</div>${input('방향(°)','heading',r.heading,'number','step=".1"')}${input('벽 색상','color',r.color,'color')}${input('기본지도 에셋 ID (선택)','source_id',r.source_id||'')}<label class="check"><input name="hidden" type="checkbox" ${r.hidden?'checked':''}> 철거 / 숨김</label><p class="hint">기본지도 ID가 있으면 해당 모델의 숨김과 파사드 레이어를 관리합니다. 원본 모델의 메시 자체는 변형하지 않습니다.</p>`;
 if(tab==='assets'&&r.source_record)h+='<p class="hint">확정 파사드의 참조 위치입니다. 표면 실측 규격이 없는 항목의 3m 값과 깊이 0.1m는 임시 미리보기용이며, 실제 매장 크기가 아닙니다. 서울역 임시 변경은 별도 윤곽으로 표시하고 기존 모델은 유지합니다.</p>';
 if(tab==='facades')h=`<h2>${esc(r.name)}</h2>`+select('적용할 면','side',[['front','정면'],['right','우측면'],['back','후면'],['left','좌측면']],'front')+input('이미지 주소','facade_url',r.facades?.front||'','text','placeholder="https://… 또는 업로드"')+'<label>사진 업로드 (PNG/JPEG · 4MB)<input type="file" id="facadeFile" accept="image/png,image/jpeg"></label><img id="facadePreview" alt="파사드 미리보기" '+(r.facades?.front?`src="${esc(r.facades.front)}"`:'hidden')+'><p class="hint">정면을 남쪽으로 두고 방향각만큼 회전합니다. 원근 보정된 사진을 권장합니다.</p>';
 if(tab==='points')h+=select('포인트 역할','role',Object.entries(roles).map(([k,v])=>[k,v[0]]),r.role)+`<button type="button" id="captureArea">${r.area?'영역 다시 지정':'출도착 영역 지정'}</button>${r.area?'<button type="button" id="clearArea">영역 해제 · 점으로</button>':''}<p class="hint" id="areaHint">${r.area?`${r.area.length}개 꼭짓점 영역`:'영역은 출발·도착 역할에서만 지정합니다.'}</p>`;
 if(tab==='connections')h+=select('이동시설','kind',[['stairs','계단'],['escalator','에스컬레이터'],['elevator','엘리베이터']],r.kind)+select('통행 방향','direction',[['both','양방향 / 모든 선택 층 연결'],['forward','선택 목록 순서의 정방향']],r.direction)+'<fieldset><legend>연결할 층간접속점</legend>'+project.points.filter(p=>p.role==='connection').map(p=>`<label class="check"><input name="connectionPoints" type="checkbox" value="${esc(p.id)}" ${r.point_ids.includes(p.id)?'checked':''}> ${esc(p.floor+' · '+p.name)}</label>`).join('')+'</fieldset>';
 if(tab==='routes')h+=`<ol class="route-order">${r.point_ids.map((id,i)=>{const p=project.points.find(p=>p.id===id);return `<li><span>${esc(p?`${p.floor} · ${p.name}`:id)}</span><button type="button" data-order="${i}" data-delta="-1" aria-label="위로">↑</button><button type="button" data-order="${i}" data-delta="1" aria-label="아래로">↓</button><button type="button" data-remove="${i}" aria-label="포인트 제거">×</button></li>`;}).join('')}</ol>`+input('다음 포인트 ID (지도에서 선택 가능)','nextPoint','')+'<button id="appendPoint" type="button">＋ 순서에 추가</button>';
 if(tab==='observations')h=select('출도착 원점','origin_id',[...(project.origins||[]),...project.points.filter(p=>p.role==='origin')].map(p=>[p.id,p.name]),r.origin_id)+input('기준일','date',r.date,'date','required')+select('집계 시간','hour',[['','일 전체'],...Array.from({length:24},(_,i)=>[String(i),`${i}시`])],r.hour===null?'':String(r.hour))+input('진입량','arrivals',r.arrivals,'number','min="0" required')+input('이탈량','departures',r.departures,'number','min="0" required')+select('값의 성격','value_class',[['observed','관측값'],['estimated','추정값']],r.value_class)+`<label>출처·추정 기준<textarea name="method" rows="4">${esc(r.method)}</textarea></label>`+(saveLocked(project)?'<button id="hourlyData" type="button">이 원점의 시간별 자료 보기</button><div id="hourlyResult"></div>':'');
 if(tab==='changes')h+=`<label>구조 설정 JSON<textarea name="config" rows="18">${esc(JSON.stringify(r.config,null,2))}</textarea></label><p class="hint">이 설정은 원본 렌더러 구성입니다. 임시 JSON 수정은 지도에 즉시 재구축하지 않으며, 서울역 서버 저장은 잠겨 있습니다.</p>`;
 if(tab==='facilities')h+=input('시설 종류','category',r.category||'')+input('영업시간','hours',r.hours||'')+input('연락처','contact',r.contact||'')+input('보행 출입점 ID','access_id',r.access_id||'')+`<label class="check"><input name="active" type="checkbox" ${r.active?'checked':''}> 안내·관리 대상</label><label>시설 안내<textarea name="notes">${esc(r.notes)}</textarea></label><p class="hint">${esc(r.floor)} · 원본 ${esc(r.source_id)}${r.position?'':' · 위치 미등록'}</p><details><summary>상품·원본 상세 정보</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`;
 if(tab==='origins')h+=input('교통수단 / 모드','mode',r.mode||'')+`<label class="check"><input name="active" type="checkbox" ${r.active?'checked':''}> 사용</label><label>자료 메모<textarea name="notes">${esc(r.notes)}</textarea></label><fieldset><legend>연결할 실내 출도착점</legend>${project.points.filter(p=>p.role==='origin').map(p=>`<label class="check"><input name="entryPoints" type="checkbox" value="${esc(p.id)}" ${p.origin_ids?.includes(r.id)?'checked':''}>${esc(p.name)}</label>`).join('')}</fieldset>`;
 return h+`<div class="form-actions"><button class="primary" type="submit">변경 적용</button>${tab==='facades'?'':`<button type="button" id="removeRecord">등록 해제</button>`}</div>`;
}
function renderList(){const rows=project[key()]||[],q=recordQuery.toLowerCase(),filtered=rows.filter(r=>!q||[r.name,r.id,r.floor,r.category,r.role,r.date,r.origin_id].join(' ').toLowerCase().includes(q));$('#recordCount').textContent=`${rows.length.toLocaleString()}개 등록 · 검색 ${filtered.length.toLocaleString()}개${filtered.length>150?' · 상위 150개 표시':''}`;$('#recordList').innerHTML=filtered.slice(0,150).map(r=>`<button data-record="${esc(r.id)}" class="record ${r.id===selected?'selected':''}"><strong>${esc(r.name||[r.date,r.hour===null?'일 전체':r.hour+'시'].join(' · '))}</strong><small>${esc(r.floor||r.id)}${r.hidden?' · 숨김':r.active===false?' · 등록 해제':''}</small></button>`).join('')||'<p class="empty">검색 결과가 없습니다.</p>';}
function render(){const meta=categories[tab];$('#tabCaption').textContent=meta[0];$('#tabTitle').textContent=meta[1];$('#tabHelp').textContent=meta[2];document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));$('#addRecord').hidden=['facades','changes'].includes(tab);renderList();const r=record();$('#recordForm').innerHTML=r?fields(r):'<p class="empty">항목을 선택하거나 추가하세요.</p>';$('#recordForm').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=!canEdit);bindForm();syncHeader();scene?.select?.({kind:tab,id:selected});}
function applyForm({quiet=false}={}){const r=record();if(!r||!canEdit)return true;const f=$('#recordForm'),fd=new FormData(f),candidate=structuredClone(r);if(fd.has('name'))candidate.name=fd.get('name');if(['assets','points'].includes(tab)){candidate.floor=fd.get('floor');candidate.position=['lon','lat','height'].map(n=>Number(fd.get(n)));}
 if(tab==='assets'){candidate.size=['width','depth','sizeHeight'].map(n=>Number(fd.get(n)));candidate.heading=Number(fd.get('heading'));candidate.color=fd.get('color');candidate.hidden=fd.has('hidden');candidate.source_id=fd.get('source_id').trim()||undefined;}
 if(tab==='facades'){candidate.facades||={};const url=fd.get('facade_url').trim();if(url)candidate.facades[fd.get('side')]=url;else delete candidate.facades[fd.get('side')];}
 if(tab==='points'){candidate.role=fd.get('role');if(candidate.role!=='origin')delete candidate.area;}
 if(tab==='connections'){candidate.kind=fd.get('kind');candidate.direction=fd.get('direction');candidate.point_ids=fd.getAll('connectionPoints');}
 if(tab==='observations')Object.assign(candidate,{origin_id:fd.get('origin_id'),date:fd.get('date'),hour:fd.get('hour')===''?null:Number(fd.get('hour')),arrivals:Number(fd.get('arrivals')),departures:Number(fd.get('departures')),value_class:fd.get('value_class'),method:fd.get('method')});
 if(tab==='changes'){try{candidate.config=JSON.parse(fd.get('config'));}catch{notice('구조 설정 JSON 형식을 확인하세요.');return false;}}
 if(tab==='facilities')for(const k of ['category','hours','contact','access_id','notes'])candidate[k]=fd.get(k)||'';
 if(tab==='origins'){candidate.mode=fd.get('mode');candidate.notes=fd.get('notes');}
 if(['origins','facilities'].includes(tab))candidate.active=fd.has('active');
 if(tab==='connections'&&JSON.stringify(r.point_ids)!==JSON.stringify(candidate.point_ids))delete candidate.path;const next=structuredClone(project);next[key()][next[key()].findIndex(x=>x.id===r.id)]=candidate;let mappingChanged=false;if(tab==='origins')for(const p of next.points.filter(p=>p.role==='origin')){const linked=fd.getAll('entryPoints').includes(p.id);if(linked!==(p.origin_ids||[]).includes(r.id)){mappingChanged=true;p.origin_ids=[...(p.origin_ids||[]).filter(id=>id!==r.id),...(linked?[r.id]:[])];}}try{validateProject(next);}catch(e){notice(e.message);return false;}const differs=mappingChanged||JSON.stringify(r)!==JSON.stringify(candidate);if(differs)candidate.preview_changed=true;project=next;if(differs)changed();if(!quiet)notice(saveLocked(project)?'서울역 임시 편집에 적용했습니다. 원본에는 저장되지 않습니다.':'변경 레이어에 적용했습니다. 서버 저장으로 보관하세요.');return true;
}
function bindForm(){const f=$('#recordForm');f.onsubmit=e=>{e.preventDefault();if(applyForm())render();};f.oninput=()=>{dirty=true;status();};
 const side=f.elements.side;if(side)side.onchange=()=>{const r=record();f.elements.facade_url.value=r.facades?.[side.value]||'';const im=$('#facadePreview');im.hidden=!f.elements.facade_url.value;if(!im.hidden)im.src=f.elements.facade_url.value;};
 const file=$('#facadeFile');if(file)file.onchange=async()=>{try{const image=file.files[0],selectedSide=f.elements.side.value;if(!image)return;if(saveLocked(project)){notice('심사 기간에는 서울역 사진 업로드가 잠겨 있습니다. 이미지 주소 변경은 임시로 검토할 수 있습니다.');return;}if(!projectId){await save({skipForm:true});}const res=await fetch(`/api/projects/${projectId}/files`,{method:'POST',body:image});const v=await res.json();if(!res.ok)throw Error(v.error);const current=$('#recordForm');current.elements.side.value=selectedSide;current.elements.facade_url.value=v.url;$('#facadePreview').src=v.url;$('#facadePreview').hidden=false;dirty=true;status();notice('업로드 완료 · 변경 적용 후 서버 저장하세요.');}catch(e){notice(e.message);}};
 if($('#hourlyData'))$('#hourlyData').onclick=async()=>{try{const v=await api('/api/seoul/hourly?origin='+encodeURIComponent(record().origin_id));$('#hourlyResult').innerHTML='<pre>'+esc(JSON.stringify(v,null,2))+'</pre>';}catch(e){notice(e.message);}};
 const area=$('#captureArea');if(area)area.onclick=()=>{if(f.elements.role.value!=='origin'){notice('역할을 출발·도착으로 선택하세요.');return;}areaCapture=[];$('#areaHint').innerHTML='지도에서 꼭짓점을 3개 이상 클릭하세요. <button type="button" id="finishArea">영역 확정</button>';$('#finishArea').onclick=()=>{if(areaCapture.length<3)return notice('3개 이상 지정하세요.');record().area=areaCapture;record().role='origin';areaCapture=null;changed();render();};};
 if($('#clearArea'))$('#clearArea').onclick=()=>{delete record().area;changed();render();};
 if($('#appendPoint'))$('#appendPoint').onclick=()=>{record().name=f.elements.name.value;const id=f.elements.nextPoint.value;if(!project.points.some(p=>p.id===id))return notice('등록된 포인트 ID를 선택하세요.');record().point_ids.push(id);record().preview_changed=true;changed();render();};
 f.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{record().name=f.elements.name.value;const a=record().point_ids,i=+b.dataset.order,j=i+(+b.dataset.delta);if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];changed();render();});
 f.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{record().point_ids.splice(+b.dataset.remove,1);changed();render();});
 if($('#removeRecord'))$('#removeRecord').onclick=()=>{dialog('<h2>등록을 해제할까요?</h2><p>서버에 저장하기 전까지는 기존 저장본을 다시 불러올 수 있습니다. 철거된 구조물은 등록 해제 대신 숨김을 권장합니다.</p><button id="confirmRemove" class="primary">등록 해제</button>');$('#confirmRemove').onclick=()=>{const next=structuredClone(project);next[key()]=next[key()].filter(r=>r.id!==selected);try{validateProject(next);}catch(e){notice('다른 경로·연결에서 참조 중입니다. '+e.message);return;}project=next;selected=project[key()][0]?.id;$('#dialog').close();changed();render();};};
}
function selectRecord(id){selected=id;render();const r=record();const start=project.points.find(p=>p.id===r?.point_ids?.[0]),targetFloor=r?.floor||start?.floor;if(targetFloor&&stationOf(project).floors.includes(targetFloor)){$('#floor').value=targetFloor;scene?.setFloor(targetFloor);}const p=r?.position||start?.position;if(p)scene?.focus(p);}
$('#recordList').onclick=e=>{const b=e.target.closest('[data-record]');if(b){if(record()&&!applyForm({quiet:true}))return;selectRecord(b.dataset.record);}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(record()&&!applyForm({quiet:true}))return;areaCapture=null;tab=b.dataset.tab;recordQuery='';$('#recordSearch').value='';selected=project[key()]?.[0]?.id;render();});
$('#addRecord').onclick=()=>{if(!canEdit)return notice('공개 프로젝트를 먼저 복사하세요.');if(record()&&!applyForm({quiet:true}))return;const station=stationOf(project),id=crypto.randomUUID(),floor=$('#floor').value,p=lastPick?.position||[...station.centre.slice(0,2),station.heights[floor]];let r;
 if(tab==='assets')r={id,name:'새 구조물',floor,position:p,size:[4,3,3],heading:0,color:'#73a194',hidden:false,facades:{}};
 if(tab==='points')r={id,name:'새 포인트',floor,position:p,role:'via'};
 if(tab==='facilities')r={id,name:'새 시설',floor,position:p,category:'안내',hours:'',contact:'',notes:'',active:true};
 if(tab==='origins')r={id,name:'새 유동인구 원점',mode:'도보',notes:'',active:true};
 if(tab==='connections'){const pts=project.points.filter(p=>p.role==='connection');if(new Set(pts.map(p=>p.floor)).size<2)return notice('서로 다른 층의 층간접속점을 먼저 2개 이상 등록하세요.');r={id,name:'새 층간연결',kind:'elevator',point_ids:[pts[0],pts.find(p=>p.floor!==pts[0].floor)].map(p=>p.id),direction:'both'};}
 if(tab==='routes'&&project.points.length<2)return notice('경로를 이을 포인트를 먼저 2개 이상 등록하세요.');if(tab==='routes')r={id,name:'새 이동동선',point_ids:project.points.slice(0,2).map(p=>p.id)};
 if(tab==='observations'&&!project.points.some(p=>p.role==='origin'))return notice('출발·도착 포인트를 먼저 등록하세요.');if(tab==='observations')r={id,origin_id:project.points.find(p=>p.role==='origin')?.id||'',date:new Date().toISOString().slice(0,10),hour:null,arrivals:0,departures:0,value_class:'observed',method:''};
 if(r){project[key()].push(r);selected=id;changed();render();}};
async function save({skipForm=false}={}){if(saveLocked(project))throw Error('심사 기간 서울역의 서버 저장은 잠겨 있습니다. 임시 편집안은 JSON으로 내보내세요.');if(!skipForm&&record()&&!applyForm({quiet:true}))throw Error('선택 항목을 확인하세요.');project.name=$('#projectName').value.trim();validateProject(project);if(!projectId||!canEdit){const v=await api('/api/projects','POST',{project});projectId=v.id;revision=v.revision;canEdit=true;shared=false;history.replaceState(null,'','?project='+projectId);}else{const v=await api('/api/projects/'+projectId,'PUT',{project,revision,shared});revision=v.revision;}dirty=false;status();render();return{id:projectId,revision};}
$('#saveProject').onclick=()=>save().then(()=>notice('서버 저장 완료')).catch(e=>notice(e.message));
$('#projectName').oninput=()=>{project.name=$('#projectName').value;dirty=true;status();};
function exportProject(){if(record())applyForm({quiet:true});const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ya-nerd-station-project.json';a.click();URL.revokeObjectURL(url);}
$('#exportProject').onclick=exportProject;
async function load(v){project=v.project;project.origins||=[];project.facilities||=[];project.changes||=[];projectId=v.id||null;revision=v.revision||0;canEdit=v.canEdit!==false;shared=!!v.shared;dirty=false;lastPick=null;selected=project[key()][0]?.id;render();await scene?.connect(project);}
function guard(action){if(!dirty)return action();dialog('<h2>저장하지 않은 변경이 있습니다</h2><p>JSON으로 내보내거나 서버에 저장한 뒤 다른 프로젝트를 여세요.</p><button id="discardChanges">변경 버리고 계속</button>');$('#discardChanges').onclick=()=>{$('#dialog').close();action();};}
$('#newProject').onclick=()=>guard(()=>{history.replaceState(null,'',location.pathname+(location.search.includes('scene=local')?'?scene=local':''));load({project:daejeonProject()});});
$('#openProjects').onclick=()=>guard(async()=>{try{const list=await api('/api/projects');dialog('<h2>이 브라우저의 프로젝트</h2><p>서버에 저장되며, 이 브라우저의 편집 쿠키로 접근합니다. 계정 로그인 기능은 아닙니다.</p>'+list.map(p=>`<button class="record" data-load="${p.id}">${esc(p.name)} <small>v${p.revision} · ${p.shared?'공개':'비공개'}</small></button>`).join(''));$('#dialogContent').querySelectorAll('[data-load]').forEach(b=>b.onclick=async()=>{try{const v=await api('/api/projects/'+b.dataset.load);history.replaceState(null,'','?project='+v.id);await load(v);$('#dialog').close();}catch(e){notice(e.message);}});}catch(e){notice(e.message);}});
$('#importProject').onchange=e=>{const file=e.target.files[0];if(!file)return;guard(async()=>{try{if(file.size>20_000_000)throw Error('JSON은 20MB까지 가능합니다.');const v=validateProject(JSON.parse(await file.text()));await load({project:v});history.replaceState(null,'','/');dirty=true;status();notice('새 초안으로 가져왔습니다. 서버 저장으로 별도 보관하세요.');}catch(e){notice(e.message);}});e.target.value='';};
$('#share').onclick=async()=>{if(!canEdit)return notice('공개 프로젝트는 복사한 뒤 공유하세요.');dialog(`<h2>프로젝트 공개 링크</h2><p>공개하면 시설 정보·사진·연계 데이터를 링크가 있는 누구나 볼 수 있습니다. 공개 권한이 있는 자료인지 확인하세요. 다른 사용자는 복사 후 편집할 수 있습니다.</p><label class="check"><input id="shareEnabled" type="checkbox" ${shared?'checked':''}> 이 프로젝트 공개</label><button id="saveSharing" class="primary">공개 설정 저장</button><p id="shareLink"></p>`);$('#saveSharing').onclick=async()=>{try{const before=shared,wanted=$('#shareEnabled').checked;shared=wanted;try{await save();if(wanted!==shared){shared=wanted;await save();}}catch(e){shared=before;throw e;}$('#shareLink').textContent=shared?location.origin+'/?project='+projectId:'공개가 해제되었습니다.';}catch(e){notice(e.message);}};};
$('#help').onclick=()=>dialog('<h2>함께 고치는 역 지도</h2><ol><li>샘플 또는 기본지도를 선택합니다.</li><li>구조물·파사드와 포인트를 등록합니다.</li><li>층간접속점을 연결한 뒤 이동동선을 순서대로 정리합니다.</li><li>연계 데이터의 출처·추정 기준을 입력합니다.</li><li>서버 저장 후 필요할 때만 공개 링크를 만듭니다.</li></ol><p>브이월드 연결은 해당 서버의 접근 정책·네트워크에 영향을 받습니다. 기본지도 데이터는 재배포하지 않습니다. 샘플은 실제 역 시설·통행가능성을 보증하지 않습니다.</p><p>이 도구는 브라우저 쿠키 기반 시연용 편집 권한을 사용합니다. 쿠키 삭제 전 JSON을 내보내세요. JSON에는 업로드 이미지의 주소만 포함됩니다. 다른 서버로 옮길 때 사진을 다시 업로드해야 합니다.</p>');
$('#floor').innerHTML=options(floors.map(f=>[f,f]),'3F');$('#floor').onchange=()=>scene?.setFloor($('#floor').value);$('#grid').onchange=()=>scene?.setGrid($('#grid').checked);$('#fit').onclick=()=>scene?.fit();
$('#source').innerHTML='<optgroup label="Station One · 연결 완료">'+options([['S202103','서울역 · 열람 / 저장 잠금'],['S201801','대전역 · 편집 가능']],project.site_id)+'</optgroup><optgroup label="VWorld 실내지도 보유 · 연결 준비 중">'+ktxCatalog.filter(s=>!stations.find(c=>c.name===s.name)).map(s=>`<option value="catalog:${esc(s.name)}">${esc(s.name)}</option>`).join('')+'</optgroup><optgroup label="기타">'+options([['sample','가상 샘플'],['custom','직접 입력 · 역 연결 JSON']],project.site_id)+'</optgroup>';
$('#recordSearch').oninput=e=>{recordQuery=e.target.value;renderList();};
async function connectStation(id){try{notice(id==='S202103'?'서울역 확정 설정 전체를 불러오는 중…':'역 설정을 여는 중…');const p=id==='S202103'?adaptSeoulSnapshot(await api('/api/seoul/snapshot'),seoulOrigin()):id==='sample'?sampleProject():stationProject(stations.find(s=>s.id===id));await load({project:p});const q=new URLSearchParams(location.search);q.delete('project');q.set('station',id);history.replaceState(null,'','?'+q);}catch(e){notice(e.message);$('#sceneStatus').textContent=e.message;}}
$('#connectSource').onclick=()=>guard(async()=>{const id=$('#source').value;if(id.startsWith('catalog:')){const name=id.slice(8);const cat=ktxCatalog.find(s=>s.name===name);dialog('<h2>'+esc(name)+' 연결 설정</h2><p>이 역은 VWorld 실내지도가 존재합니다. 연결하려면 VWorld 건물 ID(SxxxxXX)·중심 좌표·층 목록·기준 고도를 입력하세요. VWorld 3D 데이터 뷰어에서 해당 역의 tileset.json 주소를 확인할 수 있습니다.</p>'+(cat?'<p class="note">분류: '+esc(cat.category)+'</p>':'')+'<label>역 연결 JSON<textarea id="stationDescriptor" rows="10" style="width:100%">'+esc(JSON.stringify({...stations[1],name},null,2))+'</textarea></label><button id="connectCustom" class="primary">설정 검증 후 연결</button>');$('#connectCustom').onclick=async()=>{try{const s=validateStation(JSON.parse($('#stationDescriptor').value));if(s.id==='S202103'){await connectStation(s.id);}else await load({project:stationProject(s)});$('#dialog').close();}catch(e){notice(e.message);}};return;}if(id!=='custom')return connectStation(id);dialog('<h2>다른 역 연결 설정</h2><p>46개 KTX역에 VWorld 실내지도가 존재하며 같은 편집 스키마를 사용할 수 있습니다. 검증된 역 ID·층·좌표 설정을 가져오면 바로 같은 UI로 편집합니다. 지도 원본은 서버에 일괄 복제하지 않습니다.</p><label>역 연결 JSON<textarea id="stationDescriptor" rows="10" style="width:100%">'+esc(JSON.stringify({...stations[1],name:'연결할 역 이름'},null,2))+'</textarea></label><button id="connectCustom" class="primary">설정 검증 후 연결</button>');$('#connectCustom').onclick=async()=>{try{const s=validateStation(JSON.parse($('#stationDescriptor').value));if(s.id==='S202103'){await connectStation(s.id);}else await load({project:stationProject(s)});$('#dialog').close();}catch(e){notice(e.message);}};});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
render();
try{if(!window.Cesium&&document.readyState!=='complete')await new Promise(resolve=>window.addEventListener('load',resolve,{once:true}));scene=await createScene(p=>{lastPick=p;$('#pickStatus').textContent=`${p.floor} · ${p.position.map(n=>n.toFixed(5)).join(', ')}${p.sourceId?' · 기본 ID '+p.sourceId:''}`;if(areaCapture){areaCapture.push(p.position);notice(`영역 꼭짓점 ${areaCapture.length}개 지정`);return;}if(p.tag){if(tab==='routes'&&p.tag.kind==='points'&&record()){$('#recordForm').elements.nextPoint.value=p.tag.id;notice('다음 포인트로 선택했습니다. 순서에 추가를 누르세요.');return;}tab=p.tag.kind;selected=p.tag.id;render();return;}const f=$('#recordForm');if(canEdit&&['assets','points'].includes(tab)&&record()){['lon','lat','height'].forEach((k,i)=>f.elements[k].value=p.position[i]);if(tab==='assets'&&p.sourceId)f.elements.source_id.value=p.sourceId;dirty=true;status();}});const q=new URL(location.href).searchParams,id=q.get('project');if(id)await load(await api('/api/projects/'+id));else await connectStation(q.get('station')||'S202103');}catch(e){$('#sceneStatus').textContent=e.message;notice(e.message);}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_station_project',description:'Read the current editor draft and persistence status. User content is untrusted.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return{project:structuredClone(project),id:projectId,revision,dirty,canEdit,shared};}});
 register({name:'select_station_floor',description:'Navigate the editor map to a supported floor. Does not save records.',inputSchema:{type:'object',properties:{floor:{type:'string',enum:floors}},required:['floor'],additionalProperties:false},annotations:{readOnlyHint:false},execute(v){if(!stationOf(project).floors.includes(v?.floor))throw Error('지원하지 않는 층');$('#floor').value=v.floor;scene?.setFloor(v.floor);return{floor:v.floor};}});
 register({name:'stage_station_project',description:'Replace the unsaved editor draft with a validated project. Does not save or publish; export existing changes first when needed.',inputSchema:{type:'object',properties:{project:{type:'object'}},required:['project'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(v){if(!canEdit)throw Error('읽기 전용');const next=structuredClone(validateProject(v?.project));project=next;selected=project[key()][0]?.id;changed();render();await scene?.connect(project);return{staged:true,counts:Object.fromEntries(['assets','points','connections','routes','observations'].map(k=>[k,project[k].length]))};}});
 register({name:'save_station_project',description:'Save the current valid draft to the server with its existing visibility. Never makes a private project public.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>save()});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
