import {stations,stationOf,validateStation} from './stations.js';
export const floors=['B7','B6','B5','B4','B3','B2','B1','1F','2F','3F','4F','5F','RF'];
// Observed VWorld Daejeon floor heights, 2026-09-02. Not surveyed navigation clearance.
export const heights={'1F':55.69,'2F':60.34,'3F':63.48,'4F':68.37,'5F':71.66,RF:74.33};
export const roles={origin:['출발·도착','#35c978'],via:['경유포인트','#eef4f2'],connection:['층간접속','#398bef'],facility:['시설포인트','#f3be35']};
export const centre=[127.43459,36.33223,60.34];
export const coordinate=(x,y,z=60.34)=>[centre[0]+x/(111320*Math.cos(centre[1]*Math.PI/180)),centre[1]+y/111320,z];
export function stationProject(station=stations[1]){validateStation(station);return {...daejeonProject(),site_id:station.id,station:structuredClone(station),source:'vworld',name:station.name+' 공동 편집 초안',notes:'역별 설정과 변경 레이어를 독립적으로 저장합니다.',origins:[],facilities:[]};}
export function daejeonProject(){return {schema_version:1,site_id:'S201801',name:'대전역 공동 편집 초안',source:'vworld-daejeon',tileset_url:'',assets:[],points:[],connections:[],routes:[],observations:[],notes:'대전역 원본 모델 위에 독립 변경 레이어를 작성합니다. 서울역 심사본에는 반영되지 않습니다.'};}
export function sampleProject(){return {schema_version:1,name:'나의 디지털트윈 스테이션',source:'sample',tileset_url:'',assets:[{id:'shop-a',name:'샘플 매장 A',floor:'2F',position:coordinate(-12,7),size:[8,5,3],heading:0,color:'#73a194',hidden:false,facades:{}},{id:'shop-b',name:'샘플 매장 B',floor:'2F',position:coordinate(2,7),size:[8,5,3],heading:0,color:'#baa887',hidden:false,facades:{}}],points:[{id:'entry-east',name:'동쪽 출발점 (샘플)',floor:'2F',role:'origin',position:coordinate(25,-5)},{id:'via-center',name:'중앙 경유점',floor:'2F',role:'via',position:coordinate(0,-5)},{id:'entry-west',name:'서쪽 출발점 (샘플)',floor:'2F',role:'origin',position:coordinate(-25,-5)},{id:'lift-2',name:'엘리베이터 2F (샘플)',floor:'2F',role:'connection',position:coordinate(-20,10)},{id:'lift-3',name:'엘리베이터 3F (샘플)',floor:'3F',role:'connection',position:coordinate(-20,10,63.48)},{id:'shop-entry',name:'매장 A 출입점',floor:'2F',role:'facility',position:coordinate(-12,3)}],connections:[{id:'lift-demo',name:'샘플 엘리베이터',kind:'elevator',point_ids:['lift-2','lift-3'],direction:'both'}],routes:[{id:'route-demo',name:'동 → 서 샘플 경로',point_ids:['entry-east','via-center','entry-west']}],observations:[],notes:'샘플 구조물·수치는 가상의 예제입니다. 실제 서울역 시설이 아닙니다.'};}
export function validateProject(v){
 const fail=m=>{throw Error(m)};const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);const text=(s,max=500)=>typeof s==='string'&&s.length<=max;
 if(!obj(v)||v.schema_version!==1||!text(v.name,100)||!v.name.trim())fail('프로젝트 이름·스키마를 확인하세요.');
 if(!['sample','vworld-daejeon','vworld','seoul-snapshot'].includes(v.source)||v.tileset_url)fail('지원하는 역 설정을 선택하세요. 임의 서버 URL은 사용할 수 없습니다.');
 const station=validateStation(stationOf(v));if(v.site_id&&v.site_id!==station.id)fail('역 ID와 지도 설정이 다릅니다.');
 const ids=new Set();for(const k of ['assets','points','connections','routes','observations']){if(!Array.isArray(v[k])||v[k].length>(k==='points'?60000:5000))fail('항목 수를 확인하세요.');for(const r of v[k]){if(!obj(r)||!text(r.id,150)||!r.id||ids.has(r.id))fail('ID는 전체 프로젝트에서 고유해야 합니다.');ids.add(r.id);if(r.name!==undefined&&!text(r.name,300))fail('등록 이름 형식을 확인하세요.');}}
 const pos=p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite)&&Math.abs(p[0]-station.centre[0])<.03&&Math.abs(p[1]-station.centre[1])<.03&&p[2]>-200&&p[2]<1000;
 for(const r of [...v.assets,...v.points]){if(!station.floors.includes(r.floor)||!pos(r.position))fail('층·위치 좌표를 확인하세요.');}
 for(const r of v.assets){if(!Array.isArray(r.size)||r.size.length!==3||r.size.some(n=>!Number.isFinite(n)||n<=0||n>300)||!Number.isFinite(r.heading)||!/^#[0-9a-fA-F]{6}$/.test(r.color)||typeof r.hidden!=='boolean')fail('구조물 규격·색상·숨김을 확인하세요.');for(const s of Object.values(r.facades||{}))if(typeof s!=='string'||!(/^(https:\/\/|http:\/\/(127\.0\.0\.1|localhost):4196\/|\/api\/files\/|data:image\/(png|jpeg);base64,)/.test(s)))fail('파사드 이미지 주소를 확인하세요.');if(r.source_id&&!text(r.source_id,200))fail('기본지도 에셋 ID 오류');}
 const points=new Map(v.points.map(p=>[p.id,p]));for(const r of v.points){if(!roles[r.role])fail('포인트 구분 오류');if(r.area&&(r.role!=='origin'||!Array.isArray(r.area)||r.area.length<3||r.area.length>200||!r.area.every(pos)))fail('출도착 영역 좌표 오류');}
 for(const r of v.connections){if(!['stairs','escalator','elevator'].includes(r.kind)||!['both','forward'].includes(r.direction)||!Array.isArray(r.point_ids)||r.point_ids.length<2||r.point_ids.length>20||new Set(r.point_ids).size!==r.point_ids.length||!r.point_ids.every(id=>points.get(id)?.role==='connection'))fail('층간연결은 등록된 층간접속점 2개 이상을 지정하세요.');if(new Set(r.point_ids.map(id=>points.get(id).floor)).size<2)fail('서로 다른 층을 연결하세요.');}
 for(const r of v.routes){if(!Array.isArray(r.point_ids)||r.point_ids.length<2||r.point_ids.length>1000||!r.point_ids.every(id=>points.has(id)))fail('경로는 등록된 포인트를 순서대로 2개 이상 지정하세요.');for(let i=1;i<r.point_ids.length;i++){const a=r.point_ids[i-1],b=r.point_ids[i];if(points.get(a).floor!==points.get(b).floor&&!v.connections.some(c=>(c.path||c.point_ids).includes(a)&&(c.path||c.point_ids).includes(b)&&(c.direction==='both'||(c.path||c.point_ids).indexOf(a)<(c.path||c.point_ids).indexOf(b))))fail('경로의 층간 이동에 유효한 층간연결이 필요합니다.');}}
 for(const c of v.connections)if(c.path&&(!Array.isArray(c.path)||!c.path.every(id=>points.has(id))||c.path[0]!==c.point_ids[0]||c.path.at(-1)!==c.point_ids.at(-1)))fail('연결 이동면의 경유점을 확인하세요.');
 const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
 for(const r of v.observations){if((points.get(r.origin_id)?.role!=='origin'&&!(v.origins||[]).some(o=>o.id===r.origin_id))||!validDate(r.date)||r.hour!==null&&(!Number.isInteger(r.hour)||r.hour<0||r.hour>23)||![r.arrivals,r.departures].every(n=>Number.isFinite(n)&&n>=0)||!['observed','estimated'].includes(r.value_class)||!text(r.method,3000)||(r.value_class==='estimated'&&!r.method?.trim()))fail('유동 데이터의 원점·일시·값·추정 근거를 확인하세요.');}
 return v;
}
