import {connectedStation,structurePixels,validateStructure,preferredPhoto} from '../reports.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function initialStructure(report,saved){
 const st=connectedStation(report.station_key);
 return saved||{name:report.photos[preferredPhoto(report.photos)]?.caption||report.analysis?.ai?.signage_text||'',floor:report.floor,position:[...report.position.slice(0,2),st.heights[report.floor]??report.position[2]],size:[1,.6,2.2],heading:report.view?.heading||0,color:'#a9b6b0',dimension_basis:'estimated'};
}
export function structureSlot(s,side='front'){const [w,d,h]=s.size,offset={front:[0,-d/2,180],left:[-w/2,0,270],right:[w/2,0,90],back:[0,d/2,0]}[side],rad=-s.heading*Math.PI/180,[x,y,normal]=offset;return {alias:'new-structure',name:s.name,floor:s.floor,position:[s.position[0]+(x*Math.cos(rad)-y*Math.sin(rad))/(111320*Math.cos(s.position[1]*Math.PI/180)),s.position[1]+(x*Math.sin(rad)+y*Math.cos(rad))/111320,s.position[2]+h/2],surface:[['left','right'].includes(side)?d:w,h],heading:(s.heading+normal)%360,px:structurePixels(s.size,side),image:null};}
export function resizeBlurs(boxes,before,after){const sx=after[0]/before[0],sy=after[1]/before[1];return boxes.map(([x,y,w,h])=>[x*sx,y*sy,w*sx,h*sy]);}
export function structureFields(s,key){const st=connectedStation(key),field=(id,label,value,step='.1')=>'<label>'+label+'<input id="st-'+id+'" type="number" step="'+step+'" value="'+value+'"></label>';
 return '<div class="structure-info"><h3>새 구조물 초안</h3><p class="fine">정면·좌측면·우측면·후면 사진을 각각 보정해 직육면체에 입힙니다. 주변 사진은 배치 확인용입니다. 사진만으로 실제 치수나 가려진 면을 복원하지 않으므로 크기는 현장에 맞게 확인하세요.</p><div class="structure-fields">'
 +'<label>시설 이름<input id="st-name" maxlength="100" placeholder="예: AI역무원 키오스크" value="'+esc(s.name)+'"></label><label>층<select id="st-floor">'+st.floors.map(f=>'<option'+(f===s.floor?' selected':'')+'>'+f+'</option>').join('')+'</select></label>'
 +field('width','폭 (m)',s.size[0])+field('depth','깊이 (m)',s.size[1])+field('height','높이 (m)',s.size[2])+field('heading','회전 (°)',s.heading,'1')
 +field('lon','경도',s.position[0],'.000001')+field('lat','위도',s.position[1],'.000001')+field('alt','바닥 높이 (m)',s.position[2])
 +'<label>크기 근거<select id="st-basis"><option value="estimated"'+(s.dimension_basis==='estimated'?' selected':'')+'>사진 참고 추정 · 현장 확인 필요</option><option value="measured"'+(s.dimension_basis==='measured'?' selected':'')+'>실측 / 도면 확인</option></select></label><label>사진 없는 면 색<input id="st-color" type="color" value="'+s.color+'"></label></div><p class="fine">좌우는 정면을 마주 보고 섰을 때 기준입니다. 정면은 회전 0°에서 남쪽을 봅니다. 아래 ‘배치 지도 확인’을 누른 뒤 지도 바닥을 클릭하면 좌표를 옮길 수 있어요. 통행 폭·충돌 여부도 확인하세요.</p></div>';
}
export function readStructure(key){const get=id=>document.getElementById('st-'+id).value,n=id=>Number(get(id));return validateStructure({name:get('name'),floor:get('floor'),position:[n('lon'),n('lat'),n('alt')],size:[n('width'),n('depth'),n('height')],heading:n('heading'),color:get('color'),dimension_basis:get('basis')},key);}
// Perspective box preview uses the exact proposed proportions. No map, light reconstruction or AI geometry claim.
export function modelMarkup(s,image){const faces=typeof image==='string'?{front:image}:image||{},labels={front:'정면',left:'좌측면',right:'우측면',back:'후면'},k=170/Math.max(...s.size),[w,d,h]=s.size.map(n=>n*k);return '<div class="model-preview" aria-label="구조물 입체 모형"><div class="model-box" style="--w:'+w+'px;--d:'+d+'px;--h:'+h+'px;--color:'+s.color+'">'+['front','back','left','right'].map(side=>'<div class="model-'+side+'">'+(faces[side]?'<img src="'+esc(faces[side])+'" alt="보정한 '+labels[side]+'">':'')+'</div>').join('')+'<div class="model-top"></div></div></div><p class="fine model-caption">직육면체 모형 · '+s.size.join(' × ')+'m (폭·깊이·높이)<br>사진 없는 면은 단색 · 복잡한 형태 자동 복원 아님</p>';}
